import type { Metadata } from "next"
import { Outfit } from "next/font/google"
import "./globals.css"
 
import { ThemeProvider } from "next-themes"
import { Toaster } from "@/components/ui/sonner"
import { ChatWidget } from "@/components/chatbot/ChatWidget"
 
const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  subsets: ["latin"],
})
 
export const metadata: Metadata = {
  title: "NextStep",
  description: "Generated by create next app",
}
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const chatbotConfig = {
    // ✅ Endpoint đúng là /api/chat (prefix /api từ main.py)
    webhookUrl: `${process.env.NEXT_PUBLIC_CHATBOT_API_URL ?? "https://chatbot-ns2-pq3z.onrender.com"}/api/chat`,
    botName: "NextSteps AI",
    botAvatar: "/bot_avatar.jpg",
    theme: {
      primaryColor: "#3b82f6",
      backgroundColor: "#ffffff",
      userBubbleColor: "#3b82f6",
      botBubbleColor: "#f3f4f6",
    },
  }
 
  return (
    <html lang="vi" suppressHydrationWarning>
      <body className={`${outfitSans.variable} antialiased font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableColorScheme
          disableTransitionOnChange
        >
          {children}
          <ChatWidget config={chatbotConfig} />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
